name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Set up permissions for workspace
        run: |
          sudo chmod -R 777 /home/ubuntu/actions-runner/_work/_temp
          sudo chmod -R 777 /home/ubuntu/actions-runner/_work/Cornerstone_Ecom

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm ci

      - name: Create .env file
        run: |
          touch .env
          echo "${{ secrets.PROD }}" > .env

      - name: Restart PM2 process
        run: pm2 restart Cornerstone
